### ISSUE TITLE
Docs Update

### ISSUE THREAD

**Issue by Bube787** [truelockmc/PC-Optimus#6]
Would be really cool if you could update your docs <3

**Comment by truelockmc** [comment]
Done! Thanks for reminding me : )

https://github.com/truelockmc/PC-Optimus/blob/main/Documentation/Python%20Code%20Doc.md

**Comment by truelockmc** [comment]
Done! Thanks for reminding me : )

https://github.com/truelockmc/PC-Optimus/blob/main/Documentation/Python%20Code%20Doc.md
